server:
  port: ${HTTP_PLATFORM_PORT:8888}

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
  context-path: /admin
  health:
    refresh:
      enabled: false
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

spring:
  cloud:
    config:
      server:
        git:
          uri: ${REPO:file:///C:/oss/configs/}
          force-pull: true
          cloneOnStart: true
          searchPaths: ${ASPNETCORE_ENVIRONMENT:default}
---
spring:
  profiles: cloud
eureka:
  password: ${EUREKA_SPRING_SECURITY_USER_PASSWORD:GTPRocks!}
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:https://eurekaUser:${eureka.password:}@${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/

